Check if commit happens despite pytet failures

diff --git a/.github/actions/run-examples/action.yml b/.github/actions/run-examples/action.yml
--- a/.github/actions/run-examples/action.yml
+++ b/.github/actions/run-examples/action.yml
@@ -80,6 +80,7 @@ runs:
       run: |
         cat tests/test_examples_run.yaml
         py.test -v --capture=tee-sys -rfE -s tests/test_examples_run.py --disable-pytest-warnings
+        echo "TEST_EXIT_CODE=$?" >> $GITHUB_ENV
     
     # Commit the results if update results
     - name: Push new results to branch
@@ -105,3 +106,11 @@ runs:
               }
           }
         commitChange: true
+    
+    - name: Check if pytest passed
+      shell: bash
+      run: |
+        if [ "$TEST_EXIT_CODE" -ne 0 ]; then
+          echo "❌ Pytest failed, check for output."
+          exit $TEST_EXIT_CODE
+        fi
