Test set +e

diff --git a/.github/actions/run-examples/action.yml b/.github/actions/run-examples/action.yml
--- a/.github/actions/run-examples/action.yml
+++ b/.github/actions/run-examples/action.yml
@@ -93,11 +93,18 @@ runs:
     - name: Run tests
       shell: bash
       run: |
-        cat tests/test_examples_run.yaml
-        py.test -v --capture=tee-sys -rfE -s tests/test_examples_run.py --disable-pytest-warnings
-        EXIT_CODE=$?
-        echo "TEST_RESULT=$([ $EXIT_CODE -eq 0 ] && echo PASSED || echo FAILED)" >> $GITHUB_ENV
-        exit 0
+        cat tests/test_examples_run.yaml        
+        (
+          set +e
+          py.test -v --capture=tee-sys -rfE -s tests/test_examples_run.py --disable-pytest-warnings
+          EXIT_CODE=$?
+
+          if [ $EXIT_CODE -eq 0 ]; then
+            echo "TEST_RESULT=PASSED" >> $GITHUB_ENV
+          else
+            echo "TEST_RESULT=FAILED" >> $GITHUB_ENV
+          fi
+        )
     
     # # Commit the results if update results
     # - name: Push new results to branch
