Test 10
Signed-off-by: Jing Chen <jing.chen2@ibm.com>

diff --git a/.github/workflows/pre-run-examples.yml b/.github/workflows/pre-run-examples.yml
--- a/.github/workflows/pre-run-examples.yml
+++ b/.github/workflows/pre-run-examples.yml
@@ -21,8 +21,72 @@ jobs:
         with:
           files: |
             **.pdl
-
-      - name: List files
+      - name: List PDL files that were modified or added
         env:
           ALL_CHANGED_PDL_FILES: ${{ steps.changed-pdl-files.outputs.all_changed_files }}
         run: echo "$ALL_CHANGED_PDL_FILES"
+
+      # # Set up Ollama
+      # - name: Install Ollama and start server
+      #   shell: bash
+      #   run: |
+      #     curl -fsSL https://ollama.com/install.sh | sudo -E sh
+      # - name: Pull models in examples/
+      #   shell: bash
+      #   run: |
+      #     ollama pull granite3.2:2b
+      #     ollama pull mxbai-embed-large
+      #     ollama list
+      # - name: Check that all required models are available
+      #   shell: bash
+      #   run: |
+      #     models=("mxbai-embed-large" "granite3.2:2b")
+      #     missing=0
+      #     for model in "${models[@]}"; do
+      #       if ! ollama list | awk 'NR>1 {print $1}' | grep -q "$model"; then
+      #         echo "❌ Model $model (or substring) is missing!"
+      #         missing=1
+      #       fi
+      #     done
+
+      #     if [ "$missing" -eq 1 ]; then
+      #       exit 1
+      #     else
+      #       echo "✅ All expected models are available."
+      #     fi
+      # - name: Wait for Ollama server
+      #   shell: bash
+      #   run: |
+      #     sleep 5
+      #     time curl -i http://localhost:11434
+
+      # # Set up PDL
+      # - name: Set up Python ${{ matrix.python-version }}
+      #   uses: actions/setup-python@v5
+      #   with:
+      #     python-version: ${{ matrix.python-version }}
+      # - name: Cache pip
+      #   uses: actions/cache@v4
+      #   with:
+      #     # This path is specific to Ubuntu
+      #     path: ${{ env.pythonLocation }}
+      #     # Look to see if there is a cache hit for the setup file
+      #     key: ${{ runner.os }}-pip-new3-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-pip-new3
+      #       ${{ runner.os }}-new3
+      # - name: Install dependencies
+      #   run: pip install --upgrade --upgrade-strategy eager .[all]
+      # - name: pip list packages
+      #   run: pip list
+      # - name: show pip dependencies
+      #   run: |
+      #     pip install pipdeptree
+      #     pipdeptree -fl
+
+      # Run changed PDL files test
+      - name: Run against changed PDL files
+        run: |
+          for file in ${ALL_CHANGED_PDL_FILES}; do"
+            echo $file
+          done
