Fix 14
Signed-off-by: Jing Chen <jing.chen2@ibm.com>

diff --git a/.github/workflows/run-examples-modified.yml b/.github/workflows/run-examples-modified.yml
--- a/.github/workflows/run-examples-modified.yml
+++ b/.github/workflows/run-examples-modified.yml
@@ -14,49 +14,51 @@ jobs:
         python-version: ['3.11']
 
     steps:
-      # Free up some disk space
-    - name: Remove unnecessary files
-      run: |
-        sudo rm -rf /usr/share/dotnet
-        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+    # Sets up Ollama
+    - uses: ./.github/actions/ollama
+    #   # Free up some disk space
+    # - name: Remove unnecessary files
+    #   run: |
+    #     sudo rm -rf /usr/share/dotnet
+    #     sudo rm -rf "$AGENT_TOOLSDIRECTORY"
 
-      # Set up Ollama
-    - name: Install Ollama and start server
-      shell: bash
-      run: |
-        curl -fsSL https://ollama.com/install.sh | sudo -E sh
+    #   # Set up Ollama
+    # - name: Install Ollama and start server
+    #   shell: bash
+    #   run: |
+    #     curl -fsSL https://ollama.com/install.sh | sudo -E sh
 
-    - name: Pull models in examples/
-      shell: bash
-      run: |
-        ollama pull granite3.2:2b
-        ollama pull granite3.2:8b
-        ollama pull mxbai-embed-large
-        ollama list
+    # - name: Pull models in examples/
+    #   shell: bash
+    #   run: |
+    #     ollama pull granite3.2:2b
+    #     ollama pull granite3.2:8b
+    #     ollama pull mxbai-embed-large
+    #     ollama list
 
-    - name: Check that all required models are available
-      shell: bash
-      run: |
-        models=("mxbai-embed-large" "granite3.2:2b" "granite3.2:8b")
-        missing=0
-        for model in "${models[@]}"; do
-          if ! ollama list | awk 'NR>1 {print $1}' | grep -q "$model"; then
-            echo "❌ Model $model (or substring) is missing!"
-            missing=1
-          fi
-        done
+    # - name: Check that all required models are available
+    #   shell: bash
+    #   run: |
+    #     models=("mxbai-embed-large" "granite3.2:2b" "granite3.2:8b")
+    #     missing=0
+    #     for model in "${models[@]}"; do
+    #       if ! ollama list | awk 'NR>1 {print $1}' | grep -q "$model"; then
+    #         echo "❌ Model $model (or substring) is missing!"
+    #         missing=1
+    #       fi
+    #     done
 
-        if [ "$missing" -eq 1 ]; then
-          exit 1
-        else
-          echo "✅ All expected models are available."
-        fi
+    #     if [ "$missing" -eq 1 ]; then
+    #       exit 1
+    #     else
+    #       echo "✅ All expected models are available."
+    #     fi
 
-    - name: Wait for Ollama server
-      shell: bash
-      run: |
-        sleep 10
-        time curl -i http://localhost:11434
+    # - name: Wait for Ollama server
+    #   shell: bash
+    #   run: |
+    #     sleep 10
+    #     time curl -i http://localhost:11434
 
     # Run tests
     - uses: actions/checkout@v4
@@ -118,4 +120,4 @@ jobs:
         WATSONX_APIKEY: ${{ secrets.WATSONX_APIKEY }}
         WATSONX_URL: ${{ secrets.WATSONX_URL }}
         REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
-      run: py.test -v --capture=tee-sys -rfE -s tests/test_examples_run_new.py
+      run: py.test -v --capture=tee-sys -rfE -s tests/test_examples_run_new.py --disable-pytest-warnings
