Env test 2
Signed-off-by: Jing Chen <jing.chen2@ibm.com>

diff --git a/.github/workflows/run-examples-jing.yml b/.github/workflows/run-examples-jing.yml
--- a/.github/workflows/run-examples-jing.yml
+++ b/.github/workflows/run-examples-jing.yml
@@ -15,48 +15,66 @@ jobs:
 
     steps:
 
-    #   # Free up some disk space
-    # - name: Remove unnecessary files
-    #   run: |
-    #     sudo rm -rf /usr/share/dotnet
-    #     sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      # Free up some disk space
+    - name: Remove unnecessary files
+      run: |
+        sudo rm -rf /usr/share/dotnet
+        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
 
-    #   # Set up Ollama
-    # - name: Install Ollama and start server
-    #   shell: bash
-    #   run: |
-    #     curl -fsSL https://ollama.com/install.sh | sudo -E sh
+      # Set up Ollama
+    - name: Install Ollama and start server
+      shell: bash
+      run: |
+        curl -fsSL https://ollama.com/install.sh | sudo -E sh
 
-    # - name: Pull models in examples/
-    #   shell: bash
-    #   run: |
-    #     ollama pull granite3.2:2b
-    #     ollama pull granite3.2:8b
-    #     ollama list
+    - name: Pull models in examples/
+      shell: bash
+      run: |
+        ollama pull granite3.2:2b
+        ollama pull granite3.2:8b
+        ollama list
 
-    # - name: Check that all required models are available
-    #   shell: bash
-    #   run: |
-    #     models=("granite3.2:2b" "granite3.2:8b")
-    #     missing=0
-    #     for model in "${models[@]}"; do
-    #       if ! ollama list | awk 'NR>1 {print $1}' | grep -q "$model"; then
-    #         echo "❌ Model $model (or substring) is missing!"
-    #         missing=1
-    #       fi
-    #     done
+    - name: Check that all required models are available
+      shell: bash
+      run: |
+        models=("granite3.2:2b" "granite3.2:8b")
+        missing=0
+        for model in "${models[@]}"; do
+          if ! ollama list | awk 'NR>1 {print $1}' | grep -q "$model"; then
+            echo "❌ Model $model (or substring) is missing!"
+            missing=1
+          fi
+        done
 
-    #     if [ "$missing" -eq 1 ]; then
-    #       exit 1
-    #     else
-    #       echo "✅ All expected models are available."
-    #     fi
+        if [ "$missing" -eq 1 ]; then
+          exit 1
+        else
+          echo "✅ All expected models are available."
+        fi
 
-    # - name: Wait for Ollama server
-    #   shell: bash
-    #   run: |
-    #     sleep 10
-    #     time curl -i http://localhost:11434
+    - name: Wait for Ollama server
+      shell: bash
+      run: |
+        sleep 10
+        time curl -i http://localhost:11434
+
+    - name: Test curl
+      shell: bash
+      run: |
+        curl http://localhost:11434/api/chat -d '{
+          "model": "granite3.2:2b",
+          "messages": [
+            {
+              "role": "user",
+              "content": "Translate the word Hello to French\n"
+            }
+          ],
+          "options": {
+            "temperature": 0
+          },
+          "stop": ["\n"],
+          "stream": false
+        }'
 
     # Run tests
     - uses: actions/checkout@v4
@@ -77,9 +95,11 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -e .[all]
+        pip install -e .
     - name: pip list packages
       run: pip list
+    - name: Check pip list
+      run: pip list | grep pytest
     # - name: show pip dependencies
     #   run: |
     #     pip install pipdeptree
@@ -91,3 +111,19 @@ jobs:
     #     WATSONX_URL: ${{ secrets.WATSONX_URL }}
     #     REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
     #   run: py.test -v --capture=tee-sys -rfE -s tests/test_examples_run.py
+
+
+# curl http://localhost:11434/api/chat -d '{
+#   "model": "granite3.2:2b",
+#   "messages": [
+#     {
+#       "role": "user",
+#       "content": "Translate the word Hello to French\n"
+#     }
+#   ],
+#   "options": {
+#     "temperature": 0
+#   },
+#   "stop": ["\n"],
+#   "stream": false
+# }'
