See if can run on macos
Signed-off-by: Jing Chen <jing.chen2@ibm.com>

diff --git a/.github/workflows/run-examples-jing.yml b/.github/workflows/run-examples-jing.yml
--- a/.github/workflows/run-examples-jing.yml
+++ b/.github/workflows/run-examples-jing.yml
@@ -7,116 +7,127 @@ on: [push]
 jobs:
   tests:
     name: Execution tests
-    runs-on: ubuntu-latest
+    runs-on: macos-latest
     strategy:
       fail-fast: false
       matrix:
         python-version: ['3.11']
 
     steps:
+      # Set up ollama on macos
+      - name: Install Ollama and start server
+        uses: ai-action/setup-ollama@v1
+      - name: Pull model
+        run: |
+          ollama pull granite3.2:2b
+          curl http://localhost:11434/api/generate -d '{
+            "model": "granite3.2:2b",
+            "prompt": "Why is the sky blue?",
+            "stream": false
+          }'
 
-      # Set up Ollama
-    - name: Install Ollama and start server
-      shell: bash
-      run: |
-        curl -fsSL https://ollama.com/install.sh | sudo -E sh
+#       # Set up Ollama
+#     - name: Install Ollama and start server
+#       shell: bash
+#       run: |
+#         curl -fsSL https://ollama.com/install.sh | sudo -E sh
 
-    - name: Pull models in examples/
-      shell: bash
-      run: |
-        ollama pull granite3.2:2b
-        ollama list
+#     - name: Pull models in examples/
+#       shell: bash
+#       run: |
+#         ollama pull granite3.2:2b
+#         ollama list
 
-    - name: Check that all required models are available
-      shell: bash
-      run: |
-        models=("granite3.2:2b")
-        missing=0
-        for model in "${models[@]}"; do
-          if ! ollama list | awk 'NR>1 {print $1}' | grep -q "$model"; then
-            echo "❌ Model $model (or substring) is missing!"
-            missing=1
-          fi
-        done
+#     - name: Check that all required models are available
+#       shell: bash
+#       run: |
+#         models=("granite3.2:2b")
+#         missing=0
+#         for model in "${models[@]}"; do
+#           if ! ollama list | awk 'NR>1 {print $1}' | grep -q "$model"; then
+#             echo "❌ Model $model (or substring) is missing!"
+#             missing=1
+#           fi
+#         done
 
-        if [ "$missing" -eq 1 ]; then
-          exit 1
-        else
-          echo "✅ All expected models are available."
-        fi
+#         if [ "$missing" -eq 1 ]; then
+#           exit 1
+#         else
+#           echo "✅ All expected models are available."
+#         fi
 
-    - name: Wait for Ollama server
-      shell: bash
-      run: |
-        sleep 10
-        time curl -i http://localhost:11434
+#     - name: Wait for Ollama server
+#       shell: bash
+#       run: |
+#         sleep 10
+#         time curl -i http://localhost:11434
 
-    - name: Test curl
-      shell: bash
-      run: |
-        curl http://localhost:11434/api/chat -d '{
-          "model": "granite3.2:2b",
-          "messages": [
-            {
-              "role": "user",
-              "content": "Translate the word Hello to French\n"
-            }
-          ],
-          "options": {
-            "temperature": 0
-          },
-          "stop": ["\n"],
-          "stream": false
-        }'
+#     - name: Test curl
+#       shell: bash
+#       run: |
+#         curl http://localhost:11434/api/chat -d '{
+#           "model": "granite3.2:2b",
+#           "messages": [
+#             {
+#               "role": "user",
+#               "content": "Translate the word Hello to French\n"
+#             }
+#           ],
+#           "options": {
+#             "temperature": 0
+#           },
+#           "stop": ["\n"],
+#           "stream": false
+#         }'
 
-    # Run tests
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Cache pip
-      uses: actions/cache@v4
-      with:
-        # This path is specific to Ubuntu
-        path: ${{ env.pythonLocation }}
-        # Look to see if there is a cache hit for the setup file
-        key: ${{ runner.os }}-pip-new3-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
-        restore-keys: |
-          ${{ runner.os }}-pip-new3
-          ${{ runner.os }}-new3
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -e .
-    - name: pip list packages
-      run: pip list
-    - name: Check pip list
-      run: pip list | grep pytest
-    # - name: show pip dependencies
-    #   run: |
-    #     pip install pipdeptree
-    #     pipdeptree -fl
-    # - name: run tests
-    #   env:
-    #     WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
-    #     WATSONX_APIKEY: ${{ secrets.WATSONX_APIKEY }}
-    #     WATSONX_URL: ${{ secrets.WATSONX_URL }}
-    #     REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
-    #   run: py.test -v --capture=tee-sys -rfE -s tests/test_examples_run.py
+#     # Run tests
+#     - uses: actions/checkout@v4
+#     - name: Set up Python ${{ matrix.python-version }}
+#       uses: actions/setup-python@v5
+#       with:
+#         python-version: ${{ matrix.python-version }}
+#     - name: Cache pip
+#       uses: actions/cache@v4
+#       with:
+#         # This path is specific to Ubuntu
+#         path: ${{ env.pythonLocation }}
+#         # Look to see if there is a cache hit for the setup file
+#         key: ${{ runner.os }}-pip-new3-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
+#         restore-keys: |
+#           ${{ runner.os }}-pip-new3
+#           ${{ runner.os }}-new3
+#     - name: Install dependencies
+#       run: |
+#         python -m pip install --upgrade pip
+#         pip install -e .
+#     - name: pip list packages
+#       run: pip list
+#     - name: Check pip list
+#       run: pip list | grep pytest
+#     # - name: show pip dependencies
+#     #   run: |
+#     #     pip install pipdeptree
+#     #     pipdeptree -fl
+#     # - name: run tests
+#     #   env:
+#     #     WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
+#     #     WATSONX_APIKEY: ${{ secrets.WATSONX_APIKEY }}
+#     #     WATSONX_URL: ${{ secrets.WATSONX_URL }}
+#     #     REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
+#     #   run: py.test -v --capture=tee-sys -rfE -s tests/test_examples_run.py
 
 
-# curl http://localhost:11434/api/chat -d '{
-#   "model": "granite3.2:2b",
-#   "messages": [
-#     {
-#       "role": "user",
-#       "content": "Translate the word Hello to French\n"
-#     }
-#   ],
-#   "options": {
-#     "temperature": 0
-#   },
-#   "stop": ["\n"],
-#   "stream": false
-# }'
+# # curl http://localhost:11434/api/chat -d '{
+# #   "model": "granite3.2:2b",
+# #   "messages": [
+# #     {
+# #       "role": "user",
+# #       "content": "Translate the word Hello to French\n"
+# #     }
+# #   ],
+# #   "options": {
+# #     "temperature": 0
+# #   },
+# #   "stop": ["\n"],
+# #   "stream": false
+# # }'
